### ISSUE TITLE
REQUEST: New/Change membership for @wayneparrott

### ISSUE THREAD

**Issue by wayneparrott** [RobotWebTools/community#12]
### Request
- Are you looking to become a member? yes
- Are you looking to move from one Working Group role to another (e.g. member to reviewer)? no

User: @wayneparrott
Role: member

### Requirements

- [x ] I have reviewed the community governance model / guidelines (https://github.com/RobotWebTools/community)
- [x ] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x ] I am actively contributing to 1 or more working group subprojects

### Sponsors (if applicable)
- none atm

### List of contributions to the working group
* mostly rclnodejs & rclnodejs-cli PRs, https://github.com/pulls?q=is%3Apr+author%3Awayneparrott
* medium ros2 javascript articles - https://ros2jsguy.medium.com/
* WG attendance (as often as possible)

**Comment by emersonknapp** [comment]
Invite sent
