### ISSUE TITLE
REQUEST: New/Change membership for @audrow

### ISSUE THREAD

**Issue by audrow** [RobotWebTools/community#13]
### Request
- Are you looking to become a member? yes
- Are you looking to move from one Working Group role to another (e.g. member to reviewer)? no

User: (at)audrow
Role: member

### Requirements

- [x] I have reviewed the community governance model / guidelines (https://github.com/RobotWebTools/community)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [ ] I am actively contributing to 1 or more working group subprojects
  - Not yet

### List of contributions to the working group
- PRs reviewed / authored
  - None yet
- Issues triaged
  - None yet
- Other relevant project involvement
  - ROS 2 and other Open Robotics organizations

**Comment by amacneil** [comment]
:+1: from me

cc @emersonknapp

**Comment by emersonknapp** [comment]
Invite sent
