### ISSUE TITLE
REQUEST: New/Change membership for `achim-k`

### ISSUE THREAD

**Issue by achim-k** [RobotWebTools/community#15]
### Request
- Are you looking to become a member? -> Yes

User: achim-k
Role: Reviewer/Approver

### Requirements

- [x] I have reviewed the community governance model / guidelines (https://github.com/RobotWebTools/community)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I am actively contributing to 1 or more working group subprojects

### List of contributions to the working group
- https://github.com/RobotWebTools/rosbridge_suite/pull/793
- https://github.com/RobotWebTools/rosbridge_suite/pull/792
- https://github.com/RobotWebTools/rosbridge_suite/pull/393
- https://github.com/RobotWebTools/rosbridge_suite/pull/359
- https://github.com/RobotWebTools/roslibjs/pull/304
- https://github.com/RobotWebTools/roslibjs/pull/294
- https://github.com/RobotWebTools/roslibjs/pull/293
- https://github.com/RobotWebTools/ros3djs/pull/160
- https://github.com/RobotWebTools/ros3djs/pull/161

**Comment by defunctzombie** [comment]
I support this 👍

**Comment by amacneil** [comment]
👍
