### ISSUE TITLE
REQUEST: New/Change membership for @defunctzombie

### ISSUE THREAD

**Issue by amacneil** [RobotWebTools/community#4]
### Request
- Are you looking to become a member? yes

User: @defunctzombie
Role: approver

### Requirements

- [x] I have reviewed the community governance model / guidelines (https://github.com/{{ORGANIZATION}}/community)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I am actively contributing to 1 or more working group subprojects

### List of contributions to the working group
- WG meeting attendance

**Comment by emersonknapp** [comment]
Added
