### ISSUE TITLE
REQUEST: New/Change membership for @jtbandes

### ISSUE THREAD

**Issue by amacneil** [RobotWebTools/community#6]
### Request
- Are you looking to become a member? yes

User: @jtbandes
Role: approver

### Requirements

- [x] I have reviewed the community governance model / guidelines (https://github.com/{{ORGANIZATION}}/community)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I am actively contributing to 1 or more working group subprojects

### List of contributions to the working group
- WG meeting attendance

**Comment by emersonknapp** [comment]
@jtbandes, do you still want to be added to the org/team? Or was closing this issue intentional?

**Comment by jtbandes** [comment]
I closed it because I was added to `active` – let me know if you think there are any other relevant things I should be added to.

One I'm still missing is access to the `ros2-gbp` org – e.g. https://github.com/ros2-gbp/rosbridge_suite-release

**Comment by emersonknapp** [comment]
Added you to https://github.com/orgs/RobotWebTools/teams/approvers also. This isn't connected to any permissions yet, but as per last WG discussion we're planning to use this team group for permissions management
